#!/usr/bin/env bash
set -euo pipefail

# 这个脚本负责准备本章实验环境。
# 它也顺手展示了 Shell 里的顺序执行、source、函数复用和 here document。

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
IMAGE="images:ubuntu/24.04"
SSH_USER="ubuntu"
SSH_PRIVATE_KEY="$HOME/.ssh/id_ed25519"
SSH_PUBLIC_KEY="${SSH_PRIVATE_KEY}.pub"
INVENTORY_FILE="$SCRIPT_DIR/inventory.yml"

# Bash 函数不适合直接返回字符串，所以这里用一个全局变量把节点 IP 带回主流程。
NODE_IP=''

# 先检查本机依赖和 SSH 密钥是否就绪。
command -v incus >/dev/null 2>&1 || { echo 'ERROR: 缺少命令 incus' >&2; exit 1; }
command -v ssh >/dev/null 2>&1 || { echo 'ERROR: 缺少命令 ssh' >&2; exit 1; }
[[ -f "$SSH_PRIVATE_KEY" ]] || { echo "ERROR: 找不到私钥文件：$SSH_PRIVATE_KEY" >&2; exit 1; }
[[ -f "$SSH_PUBLIC_KEY" ]] || { echo "ERROR: 找不到公钥文件：$SSH_PUBLIC_KEY" >&2; exit 1; }
incus list >/dev/null 2>&1 || { echo 'ERROR: 当前用户无法访问 Incus，请先确认 incus-admin 组权限是否生效' >&2; exit 1; }

# 先把本机公钥读到变量里，后面会注入到容器用户的 authorized_keys。
PUBKEY="$(cat "$SSH_PUBLIC_KEY")"

# 单节点准备逻辑被拆到 scripts 目录，主脚本这里只负责整体流程编排。
# shellcheck source=../scripts/prepare_node.sh
. "$SCRIPT_DIR/../scripts/prepare_node.sh"

# 依次准备两个节点，逻辑完全一样，所以复用同一个函数。
prepare_node node1
NODE1_IP="$NODE_IP"
prepare_node node2
NODE2_IP="$NODE_IP"

# 最后根据真实 IP 生成 inventory，后面的 playbook 直接复用它。
cat > "$INVENTORY_FILE" <<EOF_INVENTORY
# Generated by prepare.sh
all:
  vars:
    ansible_connection: ssh
    ansible_user: $SSH_USER
    ansible_port: 22
    ansible_ssh_private_key_file: $SSH_PRIVATE_KEY
  children:
    incus_nodes:
      hosts:
        node1:
          ansible_host: $NODE1_IP
        node2:
          ansible_host: $NODE2_IP
EOF_INVENTORY

echo '==> 完成'
echo "==> 已生成：$INVENTORY_FILE"
